name = "Timestream"
uuid = "ce82053c-fa70-4f37-af49-87ab44846bd9"
authors = ["klangner <klangner@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AWS = "fbe9abb3-538b-5e4e-ba9e-bc94f4f92ebc"

[compat]
julia = "1.6"
AWS = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
